comment:
  behavior: default
  hide_project_coverage: false
  layout: ' diff, flags, files'
  require_base: false
  require_head: true
coverage:
  status:
    project:
      default:
        target: 100.0
        threshold: 1.0
