coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
