// Code generated by command: go run asm.go -out checksum_amd64.s -stubs checksum_amd64.go. DO NOT EDIT.

//go:build amd64

package hash

// calculate RFC 1071 internet checksum for a byte slice
func checksum(data []byte) (sum uint16)
